### PR TITLE
You done have to merge this (and don't), making a new one just to notify you

### PR DESCRIPTION
**Pull request by jakeajames**

### CODE REVIEW

**Comment by LaughingQuoll** [comment]
Some things I dont want to add yet, I'll manually merge your fork with the changes I want.

**Comment by jakeajames** [comment]
How will you be aware of changes (if they happen) if you closed the Pull request? That's the only reason why I made a new one...

**Comment by LaughingQuoll** [comment]
@jakeajames added commits manually. Orientation still isnt exactly fixed but I made progress on it.

**Comment by jakeajames** [comment]
Ok, just something:
> JakeAsJames
And
> JakeAsHacks

It's either "Jake James" or "jakeashacks" or "jake**a**james"

You aren't the first to get it wrong

**Comment by jakeajames** [comment]
Also noticed this:

`if ([[objc_getClass("UIApplication") sharedApplication] _accessibilityFrontMostApplication] != nil) {
    return true;
  }
  else {
    return false;
  }`

Should be:

`if ([[objc_getClass("UIApplication") sharedApplication] _accessibilityFrontMostApplication] != nil) {
    return false;
  }
  else {
    return true;
  }`

For some reason you swapped true with false

**Comment by LaughingQuoll** [comment]
I changed the true / false around becase it gave the wrong one. On springboard the wallpaper doesnt move frame. In applications it does.

**Comment by LaughingQuoll** [comment]
And I know landscape is stuffed up. However it does work on my devices but there are a few little bits that need fixing.

**Comment by jakeajames** [comment]
For me it's the opposite 🤔
>And I know landscape is stuffed up
If you think your method is better, ok then

**Comment by LaughingQuoll** [comment]
Can you show me your landscape method vs mine in the latest build.

**Comment by jakeajames** [comment]
I just set the frame each time you open the NC (Instead of setting it only once at each respring). Didn't create a new frame at all. Check my commit with landscape support (on the second one, where I fixed the stability problem)

**Pull request closed without merging**
